-- not feasible in general: not always possible to determine operation without evaluation; e.g. halting problem
-- feasible: trivial case -- precisely the same function; Other cases -- small domains that allow for evaluation, functions returning equal constants, etc.
